/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace ISignal {
  export type VotingParametersStruct = {
    votingDelay: BigNumberish;
    votingPeriod: BigNumberish;
    executionDelay: BigNumberish;
    quorumThreshold: BigNumberish;
    proposalThreshold: BigNumberish;
    requireMembership: boolean;
  };

  export type VotingParametersStructOutput = [
    votingDelay: bigint,
    votingPeriod: bigint,
    executionDelay: bigint,
    quorumThreshold: bigint,
    proposalThreshold: bigint,
    requireMembership: boolean
  ] & {
    votingDelay: bigint;
    votingPeriod: bigint;
    executionDelay: bigint;
    quorumThreshold: bigint;
    proposalThreshold: bigint;
    requireMembership: boolean;
  };

  export type DelegationStruct = {
    delegatee: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    active: boolean;
  };

  export type DelegationStructOutput = [
    delegatee: string,
    amount: bigint,
    timestamp: bigint,
    active: boolean
  ] & { delegatee: string; amount: bigint; timestamp: bigint; active: boolean };

  export type ProposalStruct = {
    hierarchicalId: string;
    organizationId: BytesLike;
    creator: AddressLike;
    title: string;
    description: string;
    metadataURI: string;
    proposalType: BigNumberish;
    votingType: BigNumberish;
    votingPower: BigNumberish;
    state: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    executionTime: BigNumberish;
    forVotes: BigNumberish;
    againstVotes: BigNumberish;
    abstainVotes: BigNumberish;
    executionData: BytesLike;
    targetContract: AddressLike;
    executor: AddressLike;
    createdAt: BigNumberish;
    executedAt: BigNumberish;
  };

  export type ProposalStructOutput = [
    hierarchicalId: string,
    organizationId: string,
    creator: string,
    title: string,
    description: string,
    metadataURI: string,
    proposalType: bigint,
    votingType: bigint,
    votingPower: bigint,
    state: bigint,
    startTime: bigint,
    endTime: bigint,
    executionTime: bigint,
    forVotes: bigint,
    againstVotes: bigint,
    abstainVotes: bigint,
    executionData: string,
    targetContract: string,
    executor: string,
    createdAt: bigint,
    executedAt: bigint
  ] & {
    hierarchicalId: string;
    organizationId: string;
    creator: string;
    title: string;
    description: string;
    metadataURI: string;
    proposalType: bigint;
    votingType: bigint;
    votingPower: bigint;
    state: bigint;
    startTime: bigint;
    endTime: bigint;
    executionTime: bigint;
    forVotes: bigint;
    againstVotes: bigint;
    abstainVotes: bigint;
    executionData: string;
    targetContract: string;
    executor: string;
    createdAt: bigint;
    executedAt: bigint;
  };

  export type VoteStruct = {
    voter: AddressLike;
    choice: BigNumberish;
    votingPower: BigNumberish;
    timestamp: BigNumberish;
    reason: string;
    hasVoted: boolean;
    convictionTime: BigNumberish;
    convictionMultiplier: BigNumberish;
  };

  export type VoteStructOutput = [
    voter: string,
    choice: bigint,
    votingPower: bigint,
    timestamp: bigint,
    reason: string,
    hasVoted: boolean,
    convictionTime: bigint,
    convictionMultiplier: bigint
  ] & {
    voter: string;
    choice: bigint;
    votingPower: bigint;
    timestamp: bigint;
    reason: string;
    hasVoted: boolean;
    convictionTime: bigint;
    convictionMultiplier: bigint;
  };
}

export interface SignalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "BASIS_POINTS"
      | "DEFAULT_ADMIN_ROLE"
      | "EXECUTOR_ROLE"
      | "MAX_EXECUTION_DELAY"
      | "MAX_QUORUM_THRESHOLD"
      | "MAX_VOTING_PERIOD"
      | "MIN_VOTING_PERIOD"
      | "OPERATOR_ROLE"
      | "PROPOSAL_CREATOR_ROLE"
      | "SIGNAL_ADMIN_ROLE"
      | "applyConvictionDecay"
      | "calculateConvictionMultiplier"
      | "calculateVotingPower"
      | "canExecute"
      | "canVote"
      | "cancelProposal"
      | "castVote"
      | "castVoteWithConviction"
      | "createProposal"
      | "delegateVotingPower"
      | "emergencyPause"
      | "emergencyUnpause"
      | "executeProposal"
      | "getDelegatedVotingPower"
      | "getDelegations"
      | "getOrganizationProposals"
      | "getProposal"
      | "getProposalsByState"
      | "getRoleAdmin"
      | "getVote"
      | "getVotingParameters"
      | "getVotingPowerWithDelegation"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isInitialized"
      | "moduleId"
      | "onModuleDisabled"
      | "onModuleEnabled"
      | "pause"
      | "paused"
      | "registry"
      | "renounceRole"
      | "revokeRole"
      | "setVotingParameters"
      | "supportsInterface"
      | "undelegateVotingPower"
      | "unpause"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConvictionDecayApplied"
      | "ConvictionVoteCast"
      | "ModuleDisabled"
      | "ModuleEnabled"
      | "ModuleInitialized"
      | "Paused"
      | "ProposalCanceled"
      | "ProposalCanceledHierarchical"
      | "ProposalCreated"
      | "ProposalCreatedHierarchical"
      | "ProposalExecuted"
      | "ProposalExecutedHierarchical"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "VoteCast"
      | "VoteCastHierarchical"
      | "VotingParametersUpdated"
      | "VotingPowerDelegated"
      | "VotingPowerUndelegated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EXECUTION_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_QUORUM_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_CREATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIGNAL_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyConvictionDecay",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateConvictionMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateVotingPower",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "canExecute", values: [string]): string;
  encodeFunctionData(
    functionFragment: "canVote",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "castVoteWithConviction",
    values: [string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [
      BytesLike,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateVotingPower",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyUnpause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDelegatedVotingPower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDelegations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrganizationProposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getProposal", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getProposalsByState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingParameters",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingPowerWithDelegation",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "moduleId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onModuleDisabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onModuleEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVotingParameters",
    values: [BytesLike, ISignal.VotingParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "undelegateVotingPower",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EXECUTION_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_QUORUM_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_CREATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SIGNAL_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyConvictionDecay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateConvictionMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "castVoteWithConviction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegateVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDelegatedVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDelegations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrganizationProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalsByState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVotingParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingPowerWithDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moduleId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onModuleDisabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onModuleEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVotingParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "undelegateVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace ConvictionDecayAppliedEvent {
  export type InputTuple = [
    hierarchicalId: string,
    voter: AddressLike,
    oldPower: BigNumberish,
    newPower: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    hierarchicalId: string,
    voter: string,
    oldPower: bigint,
    newPower: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    hierarchicalId: string;
    voter: string;
    oldPower: bigint;
    newPower: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConvictionVoteCastEvent {
  export type InputTuple = [
    hierarchicalId: string,
    voter: AddressLike,
    choice: BigNumberish,
    votingPower: BigNumberish,
    convictionMultiplier: BigNumberish,
    convictionTime: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    hierarchicalId: string,
    voter: string,
    choice: bigint,
    votingPower: bigint,
    convictionMultiplier: bigint,
    convictionTime: bigint,
    reason: string
  ];
  export interface OutputObject {
    hierarchicalId: string;
    voter: string;
    choice: bigint;
    votingPower: bigint;
    convictionMultiplier: bigint;
    convictionTime: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModuleDisabledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModuleEnabledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModuleInitializedEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCanceledEvent {
  export type InputTuple = [
    hierarchicalId: string,
    canceler: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    hierarchicalId: string,
    canceler: string,
    reason: string
  ];
  export interface OutputObject {
    hierarchicalId: string;
    canceler: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCanceledHierarchicalEvent {
  export type InputTuple = [
    hierarchicalId: string,
    canceler: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    hierarchicalId: string,
    canceler: string,
    reason: string
  ];
  export interface OutputObject {
    hierarchicalId: string;
    canceler: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    hierarchicalId: string,
    organizationId: BytesLike,
    creator: AddressLike,
    title: string,
    proposalType: BigNumberish,
    votingType: BigNumberish,
    votingPeriod: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    hierarchicalId: string,
    organizationId: string,
    creator: string,
    title: string,
    proposalType: bigint,
    votingType: bigint,
    votingPeriod: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    hierarchicalId: string;
    organizationId: string;
    creator: string;
    title: string;
    proposalType: bigint;
    votingType: bigint;
    votingPeriod: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedHierarchicalEvent {
  export type InputTuple = [
    hierarchicalId: string,
    organizationId: BytesLike,
    creator: AddressLike,
    title: string,
    proposalType: BigNumberish,
    votingType: BigNumberish,
    votingPeriod: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    hierarchicalId: string,
    organizationId: string,
    creator: string,
    title: string,
    proposalType: bigint,
    votingType: bigint,
    votingPeriod: bigint,
    startTime: bigint,
    endTime: bigint
  ];
  export interface OutputObject {
    hierarchicalId: string;
    organizationId: string;
    creator: string;
    title: string;
    proposalType: bigint;
    votingType: bigint;
    votingPeriod: bigint;
    startTime: bigint;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [
    hierarchicalId: string,
    executor: AddressLike,
    success: boolean,
    returnData: BytesLike
  ];
  export type OutputTuple = [
    hierarchicalId: string,
    executor: string,
    success: boolean,
    returnData: string
  ];
  export interface OutputObject {
    hierarchicalId: string;
    executor: string;
    success: boolean;
    returnData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedHierarchicalEvent {
  export type InputTuple = [
    hierarchicalId: string,
    executor: AddressLike,
    success: boolean,
    returnData: BytesLike
  ];
  export type OutputTuple = [
    hierarchicalId: string,
    executor: string,
    success: boolean,
    returnData: string
  ];
  export interface OutputObject {
    hierarchicalId: string;
    executor: string;
    success: boolean;
    returnData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    hierarchicalId: string,
    voter: AddressLike,
    choice: BigNumberish,
    votingPower: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    hierarchicalId: string,
    voter: string,
    choice: bigint,
    votingPower: bigint,
    reason: string
  ];
  export interface OutputObject {
    hierarchicalId: string;
    voter: string;
    choice: bigint;
    votingPower: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastHierarchicalEvent {
  export type InputTuple = [
    hierarchicalId: string,
    voter: AddressLike,
    choice: BigNumberish,
    votingPower: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    hierarchicalId: string,
    voter: string,
    choice: bigint,
    votingPower: bigint,
    reason: string
  ];
  export interface OutputObject {
    hierarchicalId: string;
    voter: string;
    choice: bigint;
    votingPower: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingParametersUpdatedEvent {
  export type InputTuple = [
    organizationId: BytesLike,
    parameters: ISignal.VotingParametersStruct
  ];
  export type OutputTuple = [
    organizationId: string,
    parameters: ISignal.VotingParametersStructOutput
  ];
  export interface OutputObject {
    organizationId: string;
    parameters: ISignal.VotingParametersStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingPowerDelegatedEvent {
  export type InputTuple = [
    delegator: AddressLike,
    delegatee: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    delegator: string,
    delegatee: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    delegator: string;
    delegatee: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingPowerUndelegatedEvent {
  export type InputTuple = [
    delegator: AddressLike,
    delegatee: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    delegator: string,
    delegatee: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    delegator: string;
    delegatee: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Signal extends BaseContract {
  contractName: "Signal";

  connect(runner?: ContractRunner | null): Signal;
  waitForDeployment(): Promise<this>;

  interface: SignalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_EXECUTION_DELAY: TypedContractMethod<[], [bigint], "view">;

  MAX_QUORUM_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MIN_VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  PROPOSAL_CREATOR_ROLE: TypedContractMethod<[], [string], "view">;

  SIGNAL_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  applyConvictionDecay: TypedContractMethod<
    [hierarchicalId: string, voter: AddressLike],
    [void],
    "nonpayable"
  >;

  calculateConvictionMultiplier: TypedContractMethod<
    [convictionTime: BigNumberish],
    [bigint],
    "view"
  >;

  calculateVotingPower: TypedContractMethod<
    [hierarchicalId: string, voter: AddressLike, powerType: BigNumberish],
    [bigint],
    "view"
  >;

  canExecute: TypedContractMethod<[hierarchicalId: string], [boolean], "view">;

  canVote: TypedContractMethod<
    [hierarchicalId: string, voter: AddressLike],
    [boolean],
    "view"
  >;

  cancelProposal: TypedContractMethod<
    [hierarchicalId: string, reason: string],
    [void],
    "nonpayable"
  >;

  castVote: TypedContractMethod<
    [hierarchicalId: string, choice: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  castVoteWithConviction: TypedContractMethod<
    [
      hierarchicalId: string,
      choice: BigNumberish,
      convictionTime: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  createProposal: TypedContractMethod<
    [
      organizationId: BytesLike,
      title: string,
      description: string,
      metadataURI: string,
      proposalType: BigNumberish,
      votingType: BigNumberish,
      votingPower: BigNumberish,
      votingPeriod: BigNumberish,
      executionData: BytesLike,
      targetContract: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  delegateVotingPower: TypedContractMethod<
    [delegatee: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  emergencyUnpause: TypedContractMethod<[], [void], "nonpayable">;

  executeProposal: TypedContractMethod<
    [hierarchicalId: string],
    [[boolean, string] & { success: boolean; returnData: string }],
    "nonpayable"
  >;

  getDelegatedVotingPower: TypedContractMethod<
    [delegator: AddressLike],
    [bigint],
    "view"
  >;

  getDelegations: TypedContractMethod<
    [delegator: AddressLike],
    [ISignal.DelegationStructOutput[]],
    "view"
  >;

  getOrganizationProposals: TypedContractMethod<
    [organizationId: BytesLike],
    [string[]],
    "view"
  >;

  getProposal: TypedContractMethod<
    [hierarchicalId: string],
    [ISignal.ProposalStructOutput],
    "view"
  >;

  getProposalsByState: TypedContractMethod<
    [state: BigNumberish],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getVote: TypedContractMethod<
    [hierarchicalId: string, voter: AddressLike],
    [ISignal.VoteStructOutput],
    "view"
  >;

  getVotingParameters: TypedContractMethod<
    [organizationId: BytesLike],
    [ISignal.VotingParametersStructOutput],
    "view"
  >;

  getVotingPowerWithDelegation: TypedContractMethod<
    [
      organizationId: BytesLike,
      account: AddressLike,
      votingPowerType: BigNumberish
    ],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [registryAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  moduleId: TypedContractMethod<[], [string], "view">;

  onModuleDisabled: TypedContractMethod<[], [void], "nonpayable">;

  onModuleEnabled: TypedContractMethod<[], [void], "nonpayable">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setVotingParameters: TypedContractMethod<
    [organizationId: BytesLike, params: ISignal.VotingParametersStruct],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  undelegateVotingPower: TypedContractMethod<
    [delegatee: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  version: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_EXECUTION_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_QUORUM_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_CREATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SIGNAL_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "applyConvictionDecay"
  ): TypedContractMethod<
    [hierarchicalId: string, voter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateConvictionMultiplier"
  ): TypedContractMethod<[convictionTime: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateVotingPower"
  ): TypedContractMethod<
    [hierarchicalId: string, voter: AddressLike, powerType: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<[hierarchicalId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "canVote"
  ): TypedContractMethod<
    [hierarchicalId: string, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelProposal"
  ): TypedContractMethod<
    [hierarchicalId: string, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [hierarchicalId: string, choice: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "castVoteWithConviction"
  ): TypedContractMethod<
    [
      hierarchicalId: string,
      choice: BigNumberish,
      convictionTime: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      organizationId: BytesLike,
      title: string,
      description: string,
      metadataURI: string,
      proposalType: BigNumberish,
      votingType: BigNumberish,
      votingPower: BigNumberish,
      votingPeriod: BigNumberish,
      executionData: BytesLike,
      targetContract: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delegateVotingPower"
  ): TypedContractMethod<
    [delegatee: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyUnpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<
    [hierarchicalId: string],
    [[boolean, string] & { success: boolean; returnData: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDelegatedVotingPower"
  ): TypedContractMethod<[delegator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDelegations"
  ): TypedContractMethod<
    [delegator: AddressLike],
    [ISignal.DelegationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrganizationProposals"
  ): TypedContractMethod<[organizationId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [hierarchicalId: string],
    [ISignal.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalsByState"
  ): TypedContractMethod<[state: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [hierarchicalId: string, voter: AddressLike],
    [ISignal.VoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingParameters"
  ): TypedContractMethod<
    [organizationId: BytesLike],
    [ISignal.VotingParametersStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingPowerWithDelegation"
  ): TypedContractMethod<
    [
      organizationId: BytesLike,
      account: AddressLike,
      votingPowerType: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[registryAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "moduleId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onModuleDisabled"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onModuleEnabled"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVotingParameters"
  ): TypedContractMethod<
    [organizationId: BytesLike, params: ISignal.VotingParametersStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "undelegateVotingPower"
  ): TypedContractMethod<
    [delegatee: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ConvictionDecayApplied"
  ): TypedContractEvent<
    ConvictionDecayAppliedEvent.InputTuple,
    ConvictionDecayAppliedEvent.OutputTuple,
    ConvictionDecayAppliedEvent.OutputObject
  >;
  getEvent(
    key: "ConvictionVoteCast"
  ): TypedContractEvent<
    ConvictionVoteCastEvent.InputTuple,
    ConvictionVoteCastEvent.OutputTuple,
    ConvictionVoteCastEvent.OutputObject
  >;
  getEvent(
    key: "ModuleDisabled"
  ): TypedContractEvent<
    ModuleDisabledEvent.InputTuple,
    ModuleDisabledEvent.OutputTuple,
    ModuleDisabledEvent.OutputObject
  >;
  getEvent(
    key: "ModuleEnabled"
  ): TypedContractEvent<
    ModuleEnabledEvent.InputTuple,
    ModuleEnabledEvent.OutputTuple,
    ModuleEnabledEvent.OutputObject
  >;
  getEvent(
    key: "ModuleInitialized"
  ): TypedContractEvent<
    ModuleInitializedEvent.InputTuple,
    ModuleInitializedEvent.OutputTuple,
    ModuleInitializedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCanceled"
  ): TypedContractEvent<
    ProposalCanceledEvent.InputTuple,
    ProposalCanceledEvent.OutputTuple,
    ProposalCanceledEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCanceledHierarchical"
  ): TypedContractEvent<
    ProposalCanceledHierarchicalEvent.InputTuple,
    ProposalCanceledHierarchicalEvent.OutputTuple,
    ProposalCanceledHierarchicalEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreatedHierarchical"
  ): TypedContractEvent<
    ProposalCreatedHierarchicalEvent.InputTuple,
    ProposalCreatedHierarchicalEvent.OutputTuple,
    ProposalCreatedHierarchicalEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecutedHierarchical"
  ): TypedContractEvent<
    ProposalExecutedHierarchicalEvent.InputTuple,
    ProposalExecutedHierarchicalEvent.OutputTuple,
    ProposalExecutedHierarchicalEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoteCastHierarchical"
  ): TypedContractEvent<
    VoteCastHierarchicalEvent.InputTuple,
    VoteCastHierarchicalEvent.OutputTuple,
    VoteCastHierarchicalEvent.OutputObject
  >;
  getEvent(
    key: "VotingParametersUpdated"
  ): TypedContractEvent<
    VotingParametersUpdatedEvent.InputTuple,
    VotingParametersUpdatedEvent.OutputTuple,
    VotingParametersUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VotingPowerDelegated"
  ): TypedContractEvent<
    VotingPowerDelegatedEvent.InputTuple,
    VotingPowerDelegatedEvent.OutputTuple,
    VotingPowerDelegatedEvent.OutputObject
  >;
  getEvent(
    key: "VotingPowerUndelegated"
  ): TypedContractEvent<
    VotingPowerUndelegatedEvent.InputTuple,
    VotingPowerUndelegatedEvent.OutputTuple,
    VotingPowerUndelegatedEvent.OutputObject
  >;

  filters: {
    "ConvictionDecayApplied(string,address,uint256,uint256,uint256)": TypedContractEvent<
      ConvictionDecayAppliedEvent.InputTuple,
      ConvictionDecayAppliedEvent.OutputTuple,
      ConvictionDecayAppliedEvent.OutputObject
    >;
    ConvictionDecayApplied: TypedContractEvent<
      ConvictionDecayAppliedEvent.InputTuple,
      ConvictionDecayAppliedEvent.OutputTuple,
      ConvictionDecayAppliedEvent.OutputObject
    >;

    "ConvictionVoteCast(string,address,uint8,uint256,uint256,uint256,string)": TypedContractEvent<
      ConvictionVoteCastEvent.InputTuple,
      ConvictionVoteCastEvent.OutputTuple,
      ConvictionVoteCastEvent.OutputObject
    >;
    ConvictionVoteCast: TypedContractEvent<
      ConvictionVoteCastEvent.InputTuple,
      ConvictionVoteCastEvent.OutputTuple,
      ConvictionVoteCastEvent.OutputObject
    >;

    "ModuleDisabled()": TypedContractEvent<
      ModuleDisabledEvent.InputTuple,
      ModuleDisabledEvent.OutputTuple,
      ModuleDisabledEvent.OutputObject
    >;
    ModuleDisabled: TypedContractEvent<
      ModuleDisabledEvent.InputTuple,
      ModuleDisabledEvent.OutputTuple,
      ModuleDisabledEvent.OutputObject
    >;

    "ModuleEnabled()": TypedContractEvent<
      ModuleEnabledEvent.InputTuple,
      ModuleEnabledEvent.OutputTuple,
      ModuleEnabledEvent.OutputObject
    >;
    ModuleEnabled: TypedContractEvent<
      ModuleEnabledEvent.InputTuple,
      ModuleEnabledEvent.OutputTuple,
      ModuleEnabledEvent.OutputObject
    >;

    "ModuleInitialized(address)": TypedContractEvent<
      ModuleInitializedEvent.InputTuple,
      ModuleInitializedEvent.OutputTuple,
      ModuleInitializedEvent.OutputObject
    >;
    ModuleInitialized: TypedContractEvent<
      ModuleInitializedEvent.InputTuple,
      ModuleInitializedEvent.OutputTuple,
      ModuleInitializedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProposalCanceled(string,address,string)": TypedContractEvent<
      ProposalCanceledEvent.InputTuple,
      ProposalCanceledEvent.OutputTuple,
      ProposalCanceledEvent.OutputObject
    >;
    ProposalCanceled: TypedContractEvent<
      ProposalCanceledEvent.InputTuple,
      ProposalCanceledEvent.OutputTuple,
      ProposalCanceledEvent.OutputObject
    >;

    "ProposalCanceledHierarchical(string,address,string)": TypedContractEvent<
      ProposalCanceledHierarchicalEvent.InputTuple,
      ProposalCanceledHierarchicalEvent.OutputTuple,
      ProposalCanceledHierarchicalEvent.OutputObject
    >;
    ProposalCanceledHierarchical: TypedContractEvent<
      ProposalCanceledHierarchicalEvent.InputTuple,
      ProposalCanceledHierarchicalEvent.OutputTuple,
      ProposalCanceledHierarchicalEvent.OutputObject
    >;

    "ProposalCreated(string,bytes8,address,string,uint8,uint8,uint256,uint256,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalCreatedHierarchical(string,bytes8,address,string,uint8,uint8,uint256,uint256,uint256)": TypedContractEvent<
      ProposalCreatedHierarchicalEvent.InputTuple,
      ProposalCreatedHierarchicalEvent.OutputTuple,
      ProposalCreatedHierarchicalEvent.OutputObject
    >;
    ProposalCreatedHierarchical: TypedContractEvent<
      ProposalCreatedHierarchicalEvent.InputTuple,
      ProposalCreatedHierarchicalEvent.OutputTuple,
      ProposalCreatedHierarchicalEvent.OutputObject
    >;

    "ProposalExecuted(string,address,bool,bytes)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalExecutedHierarchical(string,address,bool,bytes)": TypedContractEvent<
      ProposalExecutedHierarchicalEvent.InputTuple,
      ProposalExecutedHierarchicalEvent.OutputTuple,
      ProposalExecutedHierarchicalEvent.OutputObject
    >;
    ProposalExecutedHierarchical: TypedContractEvent<
      ProposalExecutedHierarchicalEvent.InputTuple,
      ProposalExecutedHierarchicalEvent.OutputTuple,
      ProposalExecutedHierarchicalEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VoteCast(string,address,uint8,uint256,string)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoteCastHierarchical(string,address,uint8,uint256,string)": TypedContractEvent<
      VoteCastHierarchicalEvent.InputTuple,
      VoteCastHierarchicalEvent.OutputTuple,
      VoteCastHierarchicalEvent.OutputObject
    >;
    VoteCastHierarchical: TypedContractEvent<
      VoteCastHierarchicalEvent.InputTuple,
      VoteCastHierarchicalEvent.OutputTuple,
      VoteCastHierarchicalEvent.OutputObject
    >;

    "VotingParametersUpdated(bytes8,tuple)": TypedContractEvent<
      VotingParametersUpdatedEvent.InputTuple,
      VotingParametersUpdatedEvent.OutputTuple,
      VotingParametersUpdatedEvent.OutputObject
    >;
    VotingParametersUpdated: TypedContractEvent<
      VotingParametersUpdatedEvent.InputTuple,
      VotingParametersUpdatedEvent.OutputTuple,
      VotingParametersUpdatedEvent.OutputObject
    >;

    "VotingPowerDelegated(address,address,uint256,uint256)": TypedContractEvent<
      VotingPowerDelegatedEvent.InputTuple,
      VotingPowerDelegatedEvent.OutputTuple,
      VotingPowerDelegatedEvent.OutputObject
    >;
    VotingPowerDelegated: TypedContractEvent<
      VotingPowerDelegatedEvent.InputTuple,
      VotingPowerDelegatedEvent.OutputTuple,
      VotingPowerDelegatedEvent.OutputObject
    >;

    "VotingPowerUndelegated(address,address,uint256,uint256)": TypedContractEvent<
      VotingPowerUndelegatedEvent.InputTuple,
      VotingPowerUndelegatedEvent.OutputTuple,
      VotingPowerUndelegatedEvent.OutputObject
    >;
    VotingPowerUndelegated: TypedContractEvent<
      VotingPowerUndelegatedEvent.InputTuple,
      VotingPowerUndelegatedEvent.OutputTuple,
      VotingPowerUndelegatedEvent.OutputObject
    >;
  };
}
