/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace ISignal {
  export type VotingParametersStruct = {
    votingDelay: BigNumberish;
    votingPeriod: BigNumberish;
    executionDelay: BigNumberish;
    quorumThreshold: BigNumberish;
    proposalThreshold: BigNumberish;
    requireMembership: boolean;
  };

  export type VotingParametersStructOutput = [
    votingDelay: bigint,
    votingPeriod: bigint,
    executionDelay: bigint,
    quorumThreshold: bigint,
    proposalThreshold: bigint,
    requireMembership: boolean
  ] & {
    votingDelay: bigint;
    votingPeriod: bigint;
    executionDelay: bigint;
    quorumThreshold: bigint;
    proposalThreshold: bigint;
    requireMembership: boolean;
  };

  export type DelegationStruct = {
    delegator: AddressLike;
    delegatee: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    active: boolean;
  };

  export type DelegationStructOutput = [
    delegator: string,
    delegatee: string,
    amount: bigint,
    timestamp: bigint,
    active: boolean
  ] & {
    delegator: string;
    delegatee: string;
    amount: bigint;
    timestamp: bigint;
    active: boolean;
  };

  export type ProposalStruct = {
    index: BigNumberish;
    proposalId: BytesLike;
    organizationId: BytesLike;
    proposer: AddressLike;
    title: string;
    description: string;
    metadataURI: string;
    proposalType: BigNumberish;
    votingType: BigNumberish;
    votingPower: BigNumberish;
    state: BigNumberish;
    startTime: BigNumberish;
    endTime: BigNumberish;
    executionTime: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
    executionData: BytesLike;
    targetContract: AddressLike;
    requiredQuorum: BigNumberish;
    votesFor: BigNumberish;
    votesAgainst: BigNumberish;
    votesAbstain: BigNumberish;
    totalVotingPower: BigNumberish;
    executed: boolean;
    cancelled: boolean;
  };

  export type ProposalStructOutput = [
    index: bigint,
    proposalId: string,
    organizationId: string,
    proposer: string,
    title: string,
    description: string,
    metadataURI: string,
    proposalType: bigint,
    votingType: bigint,
    votingPower: bigint,
    state: bigint,
    startTime: bigint,
    endTime: bigint,
    executionTime: bigint,
    createdAt: bigint,
    updatedAt: bigint,
    executionData: string,
    targetContract: string,
    requiredQuorum: bigint,
    votesFor: bigint,
    votesAgainst: bigint,
    votesAbstain: bigint,
    totalVotingPower: bigint,
    executed: boolean,
    cancelled: boolean
  ] & {
    index: bigint;
    proposalId: string;
    organizationId: string;
    proposer: string;
    title: string;
    description: string;
    metadataURI: string;
    proposalType: bigint;
    votingType: bigint;
    votingPower: bigint;
    state: bigint;
    startTime: bigint;
    endTime: bigint;
    executionTime: bigint;
    createdAt: bigint;
    updatedAt: bigint;
    executionData: string;
    targetContract: string;
    requiredQuorum: bigint;
    votesFor: bigint;
    votesAgainst: bigint;
    votesAbstain: bigint;
    totalVotingPower: bigint;
    executed: boolean;
    cancelled: boolean;
  };

  export type VoteStruct = {
    voter: AddressLike;
    choice: BigNumberish;
    votingPower: BigNumberish;
    timestamp: BigNumberish;
    reason: string;
    convictionTime: BigNumberish;
  };

  export type VoteStructOutput = [
    voter: string,
    choice: bigint,
    votingPower: bigint,
    timestamp: bigint,
    reason: string,
    convictionTime: bigint
  ] & {
    voter: string;
    choice: bigint;
    votingPower: bigint;
    timestamp: bigint;
    reason: string;
    convictionTime: bigint;
  };
}

export interface SignalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "BASIS_POINTS"
      | "CONVICTION_MULTIPLIER_BASE"
      | "DEFAULT_ADMIN_ROLE"
      | "EXECUTOR_ROLE"
      | "MAX_EXECUTION_DELAY"
      | "MAX_QUORUM_THRESHOLD"
      | "MAX_VOTING_PERIOD"
      | "MIN_VOTING_PERIOD"
      | "OPERATOR_ROLE"
      | "PROPOSAL_CREATOR_ROLE"
      | "SIGNAL_ADMIN_ROLE"
      | "applyConvictionDecay"
      | "calculateConvictionMultiplier"
      | "calculateVotingPower"
      | "canExecute"
      | "canVote"
      | "cancelProposal"
      | "castVote"
      | "castVoteWithConviction"
      | "createProposal"
      | "delegateVotingPower"
      | "emergencyCancel"
      | "emergencyPause"
      | "emergencyUnpause"
      | "estimateGasForExecution"
      | "executeProposal"
      | "getActiveProposals"
      | "getDefaultVotingParameters"
      | "getDelegatedVotingPower"
      | "getDelegations"
      | "getExecutionETA"
      | "getProposal"
      | "getProposalCount"
      | "getProposalResult"
      | "getProposalVotes"
      | "getProposalsByOrganization"
      | "getProposalsByState"
      | "getQuorumReached"
      | "getRoleAdmin"
      | "getTimeRemaining"
      | "getVote"
      | "getVotingParameters"
      | "getVotingPower"
      | "grantRole"
      | "hasRole"
      | "hasVoted"
      | "initialize"
      | "isInitialized"
      | "isProposalActive"
      | "moduleId"
      | "onModuleDisabled"
      | "onModuleEnabled"
      | "pause"
      | "paused"
      | "previewProposalExecution"
      | "queueProposal"
      | "registry"
      | "renounceRole"
      | "revokeRole"
      | "setDefaultVotingParameters"
      | "setProposalState"
      | "setVotingParameters"
      | "supportsInterface"
      | "undelegateVotingPower"
      | "unpause"
      | "updateProposal"
      | "validateProposalParameters"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConvictionDecayApplied"
      | "ModuleDisabled"
      | "ModuleEnabled"
      | "ModuleInitialized"
      | "Paused"
      | "ProposalCancelled"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "ProposalQueued"
      | "ProposalStateChanged"
      | "ProposalUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "VoteCast"
      | "VotingParametersUpdated"
      | "VotingPowerDelegated"
      | "VotingPowerUndelegated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CONVICTION_MULTIPLIER_BASE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EXECUTOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EXECUTION_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_QUORUM_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROPOSAL_CREATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SIGNAL_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyConvictionDecay",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateConvictionMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateVotingPower",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canExecute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canVote",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "castVoteWithConviction",
    values: [BytesLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [
      BytesLike,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateVotingPower",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyCancel",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyUnpause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "estimateGasForExecution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDefaultVotingParameters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDelegatedVotingPower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDelegations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutionETA",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalResult",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalVotes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalsByOrganization",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalsByState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuorumReached",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeRemaining",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingParameters",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingPower",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isProposalActive",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "moduleId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onModuleDisabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onModuleEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "previewProposalExecution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queueProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultVotingParameters",
    values: [ISignal.VotingParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setProposalState",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVotingParameters",
    values: [BytesLike, ISignal.VotingParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "undelegateVotingPower",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateProposal",
    values: [BytesLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateProposalParameters",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CONVICTION_MULTIPLIER_BASE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EXECUTOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EXECUTION_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_QUORUM_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROPOSAL_CREATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SIGNAL_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyConvictionDecay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateConvictionMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "castVoteWithConviction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegateVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyCancel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "estimateGasForExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefaultVotingParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDelegatedVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDelegations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutionETA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalsByOrganization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalsByState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuorumReached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVotingParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProposalActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moduleId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onModuleDisabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onModuleEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "previewProposalExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultVotingParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProposalState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVotingParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "undelegateVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateProposalParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace ConvictionDecayAppliedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    voter: AddressLike,
    oldPower: BigNumberish,
    newPower: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    voter: string,
    oldPower: bigint,
    newPower: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    voter: string;
    oldPower: bigint;
    newPower: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModuleDisabledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModuleEnabledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModuleInitializedEvent {
  export type InputTuple = [registry: AddressLike];
  export type OutputTuple = [registry: string];
  export interface OutputObject {
    registry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCancelledEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    canceller: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    canceller: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    canceller: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    organizationId: BytesLike,
    proposer: AddressLike,
    title: string,
    proposalType: BigNumberish,
    votingType: BigNumberish,
    votingPower: BigNumberish,
    startTime: BigNumberish,
    endTime: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    organizationId: string,
    proposer: string,
    title: string,
    proposalType: bigint,
    votingType: bigint,
    votingPower: bigint,
    startTime: bigint,
    endTime: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    organizationId: string;
    proposer: string;
    title: string;
    proposalType: bigint;
    votingType: bigint;
    votingPower: bigint;
    startTime: bigint;
    endTime: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    success: boolean,
    returnData: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    success: boolean,
    returnData: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    success: boolean;
    returnData: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalQueuedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    executionTime: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    executionTime: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    executionTime: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalStateChangedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    oldState: BigNumberish,
    newState: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    oldState: bigint,
    newState: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    oldState: bigint;
    newState: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalUpdatedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    title: string,
    description: string,
    endTime: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    title: string,
    description: string,
    endTime: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    title: string;
    description: string;
    endTime: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    voter: AddressLike,
    choice: BigNumberish,
    votingPower: BigNumberish,
    reason: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    voter: string,
    choice: bigint,
    votingPower: bigint,
    reason: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    voter: string;
    choice: bigint;
    votingPower: bigint;
    reason: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingParametersUpdatedEvent {
  export type InputTuple = [
    organizationId: BytesLike,
    votingDelay: BigNumberish,
    votingPeriod: BigNumberish,
    executionDelay: BigNumberish,
    quorumThreshold: BigNumberish,
    proposalThreshold: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    organizationId: string,
    votingDelay: bigint,
    votingPeriod: bigint,
    executionDelay: bigint,
    quorumThreshold: bigint,
    proposalThreshold: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    organizationId: string;
    votingDelay: bigint;
    votingPeriod: bigint;
    executionDelay: bigint;
    quorumThreshold: bigint;
    proposalThreshold: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingPowerDelegatedEvent {
  export type InputTuple = [
    delegator: AddressLike,
    delegatee: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    delegator: string,
    delegatee: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    delegator: string;
    delegatee: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingPowerUndelegatedEvent {
  export type InputTuple = [
    delegator: AddressLike,
    delegatee: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    delegator: string,
    delegatee: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    delegator: string;
    delegatee: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Signal extends BaseContract {
  contractName: "Signal";

  connect(runner?: ContractRunner | null): Signal;
  waitForDeployment(): Promise<this>;

  interface: SignalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  CONVICTION_MULTIPLIER_BASE: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EXECUTOR_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_EXECUTION_DELAY: TypedContractMethod<[], [bigint], "view">;

  MAX_QUORUM_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MIN_VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  PROPOSAL_CREATOR_ROLE: TypedContractMethod<[], [string], "view">;

  SIGNAL_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  applyConvictionDecay: TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike],
    [void],
    "nonpayable"
  >;

  calculateConvictionMultiplier: TypedContractMethod<
    [convictionTime: BigNumberish],
    [bigint],
    "view"
  >;

  calculateVotingPower: TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike, powerType: BigNumberish],
    [bigint],
    "view"
  >;

  canExecute: TypedContractMethod<[proposalId: BytesLike], [boolean], "view">;

  canVote: TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike],
    [boolean],
    "view"
  >;

  cancelProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  castVote: TypedContractMethod<
    [proposalId: BytesLike, choice: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  castVoteWithConviction: TypedContractMethod<
    [
      proposalId: BytesLike,
      choice: BigNumberish,
      convictionTime: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  createProposal: TypedContractMethod<
    [
      organizationId: BytesLike,
      title: string,
      description: string,
      metadataURI: string,
      proposalType: BigNumberish,
      votingType: BigNumberish,
      votingPower: BigNumberish,
      votingPeriod: BigNumberish,
      executionData: BytesLike,
      targetContract: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  delegateVotingPower: TypedContractMethod<
    [delegatee: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyCancel: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  emergencyUnpause: TypedContractMethod<[], [void], "nonpayable">;

  estimateGasForExecution: TypedContractMethod<
    [proposalId: BytesLike],
    [bigint],
    "view"
  >;

  executeProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  getActiveProposals: TypedContractMethod<[], [string[]], "view">;

  getDefaultVotingParameters: TypedContractMethod<
    [],
    [ISignal.VotingParametersStructOutput],
    "view"
  >;

  getDelegatedVotingPower: TypedContractMethod<
    [delegator: AddressLike],
    [bigint],
    "view"
  >;

  getDelegations: TypedContractMethod<
    [delegator: AddressLike],
    [ISignal.DelegationStructOutput[]],
    "view"
  >;

  getExecutionETA: TypedContractMethod<
    [proposalId: BytesLike],
    [bigint],
    "view"
  >;

  getProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [ISignal.ProposalStructOutput],
    "view"
  >;

  getProposalCount: TypedContractMethod<[], [bigint], "view">;

  getProposalResult: TypedContractMethod<
    [proposalId: BytesLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        passed: boolean;
        forVotes: bigint;
        againstVotes: bigint;
        abstainVotes: bigint;
        quorum: bigint;
      }
    ],
    "view"
  >;

  getProposalVotes: TypedContractMethod<
    [proposalId: BytesLike],
    [
      [string[], ISignal.VoteStructOutput[]] & {
        voters: string[];
        votes: ISignal.VoteStructOutput[];
      }
    ],
    "view"
  >;

  getProposalsByOrganization: TypedContractMethod<
    [organizationId: BytesLike],
    [string[]],
    "view"
  >;

  getProposalsByState: TypedContractMethod<
    [state: BigNumberish],
    [string[]],
    "view"
  >;

  getQuorumReached: TypedContractMethod<
    [proposalId: BytesLike],
    [boolean],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTimeRemaining: TypedContractMethod<
    [proposalId: BytesLike],
    [bigint],
    "view"
  >;

  getVote: TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike],
    [ISignal.VoteStructOutput],
    "view"
  >;

  getVotingParameters: TypedContractMethod<
    [organizationId: BytesLike],
    [ISignal.VotingParametersStructOutput],
    "view"
  >;

  getVotingPower: TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike],
    [bigint],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [registryAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  isInitialized: TypedContractMethod<[], [boolean], "view">;

  isProposalActive: TypedContractMethod<
    [proposalId: BytesLike],
    [boolean],
    "view"
  >;

  moduleId: TypedContractMethod<[], [string], "view">;

  onModuleDisabled: TypedContractMethod<[], [void], "nonpayable">;

  onModuleEnabled: TypedContractMethod<[], [void], "nonpayable">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  previewProposalExecution: TypedContractMethod<
    [proposalId: BytesLike],
    [[boolean, string] & { success: boolean; returnData: string }],
    "view"
  >;

  queueProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setDefaultVotingParameters: TypedContractMethod<
    [params: ISignal.VotingParametersStruct],
    [void],
    "nonpayable"
  >;

  setProposalState: TypedContractMethod<
    [proposalId: BytesLike, newState: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVotingParameters: TypedContractMethod<
    [organizationId: BytesLike, params: ISignal.VotingParametersStruct],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  undelegateVotingPower: TypedContractMethod<
    [delegatee: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateProposal: TypedContractMethod<
    [
      proposalId: BytesLike,
      title: string,
      description: string,
      endTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  validateProposalParameters: TypedContractMethod<
    [
      organizationId: BytesLike,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish,
      votingPeriod: BigNumberish
    ],
    [boolean],
    "view"
  >;

  version: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CONVICTION_MULTIPLIER_BASE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EXECUTOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_EXECUTION_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_QUORUM_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PROPOSAL_CREATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SIGNAL_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "applyConvictionDecay"
  ): TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateConvictionMultiplier"
  ): TypedContractMethod<[convictionTime: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateVotingPower"
  ): TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike, powerType: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<[proposalId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "canVote"
  ): TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelProposal"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [proposalId: BytesLike, choice: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "castVoteWithConviction"
  ): TypedContractMethod<
    [
      proposalId: BytesLike,
      choice: BigNumberish,
      convictionTime: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      organizationId: BytesLike,
      title: string,
      description: string,
      metadataURI: string,
      proposalType: BigNumberish,
      votingType: BigNumberish,
      votingPower: BigNumberish,
      votingPeriod: BigNumberish,
      executionData: BytesLike,
      targetContract: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delegateVotingPower"
  ): TypedContractMethod<
    [delegatee: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyCancel"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyUnpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "estimateGasForExecution"
  ): TypedContractMethod<[proposalId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveProposals"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDefaultVotingParameters"
  ): TypedContractMethod<[], [ISignal.VotingParametersStructOutput], "view">;
  getFunction(
    nameOrSignature: "getDelegatedVotingPower"
  ): TypedContractMethod<[delegator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDelegations"
  ): TypedContractMethod<
    [delegator: AddressLike],
    [ISignal.DelegationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getExecutionETA"
  ): TypedContractMethod<[proposalId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BytesLike],
    [ISignal.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposalResult"
  ): TypedContractMethod<
    [proposalId: BytesLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        passed: boolean;
        forVotes: bigint;
        againstVotes: bigint;
        abstainVotes: bigint;
        quorum: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalVotes"
  ): TypedContractMethod<
    [proposalId: BytesLike],
    [
      [string[], ISignal.VoteStructOutput[]] & {
        voters: string[];
        votes: ISignal.VoteStructOutput[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalsByOrganization"
  ): TypedContractMethod<[organizationId: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProposalsByState"
  ): TypedContractMethod<[state: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getQuorumReached"
  ): TypedContractMethod<[proposalId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTimeRemaining"
  ): TypedContractMethod<[proposalId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike],
    [ISignal.VoteStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingParameters"
  ): TypedContractMethod<
    [organizationId: BytesLike],
    [ISignal.VotingParametersStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingPower"
  ): TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [proposalId: BytesLike, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[registryAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProposalActive"
  ): TypedContractMethod<[proposalId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "moduleId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onModuleDisabled"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onModuleEnabled"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "previewProposalExecution"
  ): TypedContractMethod<
    [proposalId: BytesLike],
    [[boolean, string] & { success: boolean; returnData: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "queueProposal"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDefaultVotingParameters"
  ): TypedContractMethod<
    [params: ISignal.VotingParametersStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProposalState"
  ): TypedContractMethod<
    [proposalId: BytesLike, newState: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVotingParameters"
  ): TypedContractMethod<
    [organizationId: BytesLike, params: ISignal.VotingParametersStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "undelegateVotingPower"
  ): TypedContractMethod<
    [delegatee: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProposal"
  ): TypedContractMethod<
    [
      proposalId: BytesLike,
      title: string,
      description: string,
      endTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateProposalParameters"
  ): TypedContractMethod<
    [
      organizationId: BytesLike,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: BigNumberish,
      votingPeriod: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ConvictionDecayApplied"
  ): TypedContractEvent<
    ConvictionDecayAppliedEvent.InputTuple,
    ConvictionDecayAppliedEvent.OutputTuple,
    ConvictionDecayAppliedEvent.OutputObject
  >;
  getEvent(
    key: "ModuleDisabled"
  ): TypedContractEvent<
    ModuleDisabledEvent.InputTuple,
    ModuleDisabledEvent.OutputTuple,
    ModuleDisabledEvent.OutputObject
  >;
  getEvent(
    key: "ModuleEnabled"
  ): TypedContractEvent<
    ModuleEnabledEvent.InputTuple,
    ModuleEnabledEvent.OutputTuple,
    ModuleEnabledEvent.OutputObject
  >;
  getEvent(
    key: "ModuleInitialized"
  ): TypedContractEvent<
    ModuleInitializedEvent.InputTuple,
    ModuleInitializedEvent.OutputTuple,
    ModuleInitializedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCancelled"
  ): TypedContractEvent<
    ProposalCancelledEvent.InputTuple,
    ProposalCancelledEvent.OutputTuple,
    ProposalCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalQueued"
  ): TypedContractEvent<
    ProposalQueuedEvent.InputTuple,
    ProposalQueuedEvent.OutputTuple,
    ProposalQueuedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalStateChanged"
  ): TypedContractEvent<
    ProposalStateChangedEvent.InputTuple,
    ProposalStateChangedEvent.OutputTuple,
    ProposalStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalUpdated"
  ): TypedContractEvent<
    ProposalUpdatedEvent.InputTuple,
    ProposalUpdatedEvent.OutputTuple,
    ProposalUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VotingParametersUpdated"
  ): TypedContractEvent<
    VotingParametersUpdatedEvent.InputTuple,
    VotingParametersUpdatedEvent.OutputTuple,
    VotingParametersUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VotingPowerDelegated"
  ): TypedContractEvent<
    VotingPowerDelegatedEvent.InputTuple,
    VotingPowerDelegatedEvent.OutputTuple,
    VotingPowerDelegatedEvent.OutputObject
  >;
  getEvent(
    key: "VotingPowerUndelegated"
  ): TypedContractEvent<
    VotingPowerUndelegatedEvent.InputTuple,
    VotingPowerUndelegatedEvent.OutputTuple,
    VotingPowerUndelegatedEvent.OutputObject
  >;

  filters: {
    "ConvictionDecayApplied(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      ConvictionDecayAppliedEvent.InputTuple,
      ConvictionDecayAppliedEvent.OutputTuple,
      ConvictionDecayAppliedEvent.OutputObject
    >;
    ConvictionDecayApplied: TypedContractEvent<
      ConvictionDecayAppliedEvent.InputTuple,
      ConvictionDecayAppliedEvent.OutputTuple,
      ConvictionDecayAppliedEvent.OutputObject
    >;

    "ModuleDisabled()": TypedContractEvent<
      ModuleDisabledEvent.InputTuple,
      ModuleDisabledEvent.OutputTuple,
      ModuleDisabledEvent.OutputObject
    >;
    ModuleDisabled: TypedContractEvent<
      ModuleDisabledEvent.InputTuple,
      ModuleDisabledEvent.OutputTuple,
      ModuleDisabledEvent.OutputObject
    >;

    "ModuleEnabled()": TypedContractEvent<
      ModuleEnabledEvent.InputTuple,
      ModuleEnabledEvent.OutputTuple,
      ModuleEnabledEvent.OutputObject
    >;
    ModuleEnabled: TypedContractEvent<
      ModuleEnabledEvent.InputTuple,
      ModuleEnabledEvent.OutputTuple,
      ModuleEnabledEvent.OutputObject
    >;

    "ModuleInitialized(address)": TypedContractEvent<
      ModuleInitializedEvent.InputTuple,
      ModuleInitializedEvent.OutputTuple,
      ModuleInitializedEvent.OutputObject
    >;
    ModuleInitialized: TypedContractEvent<
      ModuleInitializedEvent.InputTuple,
      ModuleInitializedEvent.OutputTuple,
      ModuleInitializedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProposalCancelled(bytes32,address,uint256)": TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;
    ProposalCancelled: TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;

    "ProposalCreated(bytes32,bytes8,address,string,uint8,uint8,uint8,uint256,uint256,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(bytes32,bool,bytes,uint256)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalQueued(bytes32,uint256,uint256)": TypedContractEvent<
      ProposalQueuedEvent.InputTuple,
      ProposalQueuedEvent.OutputTuple,
      ProposalQueuedEvent.OutputObject
    >;
    ProposalQueued: TypedContractEvent<
      ProposalQueuedEvent.InputTuple,
      ProposalQueuedEvent.OutputTuple,
      ProposalQueuedEvent.OutputObject
    >;

    "ProposalStateChanged(bytes32,uint8,uint8,uint256)": TypedContractEvent<
      ProposalStateChangedEvent.InputTuple,
      ProposalStateChangedEvent.OutputTuple,
      ProposalStateChangedEvent.OutputObject
    >;
    ProposalStateChanged: TypedContractEvent<
      ProposalStateChangedEvent.InputTuple,
      ProposalStateChangedEvent.OutputTuple,
      ProposalStateChangedEvent.OutputObject
    >;

    "ProposalUpdated(bytes32,string,string,uint256,uint256)": TypedContractEvent<
      ProposalUpdatedEvent.InputTuple,
      ProposalUpdatedEvent.OutputTuple,
      ProposalUpdatedEvent.OutputObject
    >;
    ProposalUpdated: TypedContractEvent<
      ProposalUpdatedEvent.InputTuple,
      ProposalUpdatedEvent.OutputTuple,
      ProposalUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VoteCast(bytes32,address,uint8,uint256,string,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VotingParametersUpdated(bytes8,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      VotingParametersUpdatedEvent.InputTuple,
      VotingParametersUpdatedEvent.OutputTuple,
      VotingParametersUpdatedEvent.OutputObject
    >;
    VotingParametersUpdated: TypedContractEvent<
      VotingParametersUpdatedEvent.InputTuple,
      VotingParametersUpdatedEvent.OutputTuple,
      VotingParametersUpdatedEvent.OutputObject
    >;

    "VotingPowerDelegated(address,address,uint256,uint256)": TypedContractEvent<
      VotingPowerDelegatedEvent.InputTuple,
      VotingPowerDelegatedEvent.OutputTuple,
      VotingPowerDelegatedEvent.OutputObject
    >;
    VotingPowerDelegated: TypedContractEvent<
      VotingPowerDelegatedEvent.InputTuple,
      VotingPowerDelegatedEvent.OutputTuple,
      VotingPowerDelegatedEvent.OutputObject
    >;

    "VotingPowerUndelegated(address,address,uint256,uint256)": TypedContractEvent<
      VotingPowerUndelegatedEvent.InputTuple,
      VotingPowerUndelegatedEvent.OutputTuple,
      VotingPowerUndelegatedEvent.OutputObject
    >;
    VotingPowerUndelegated: TypedContractEvent<
      VotingPowerUndelegatedEvent.InputTuple,
      VotingPowerUndelegatedEvent.OutputTuple,
      VotingPowerUndelegatedEvent.OutputObject
    >;
  };
}
