cargo-features = ["resolver"]

[workspace]
members = [
	"control",
	"signal",
	"flow",
	"sense",
	"traits",
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[patch.'https://github.com/paritytech/substrate']
frame-benchmarking = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
frame-support = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
frame-system = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-authorship = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-babe = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-balances = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-elections-phragmen = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-scheduler = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-session = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-staking = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-timestamp = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-treasury = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-vesting = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
pallet-transaction-payment = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sc-client-api = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sc-client-db = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sc-executor = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sc-executor-common = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sc-executor-wasmi = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sc-utils = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-api = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-application-crypto = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-arithmetic = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-authorship = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-blockchain = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-consensus = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-consensus-slots = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-core = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-debug-derive = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-externalities = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-inherents = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-io = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-keystore = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-npos-elections = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-panic-handler = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-runtime = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-runtime-interface = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-session = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-staking = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-state-machine = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-std = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-storage = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-tasks = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-timestamp = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-trie = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-version = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-wasm-interface = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-tracing = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }
sp-maybe-compressed-blob = { git = "https://github.com/paritytech//substrate", rev = "7a4e5163091384c4c10b6d76f5cb80dac0834f38" }

[patch.'https://github.com/paritytech/cumulus']
cumulus-primitives-core = { git = "https://github.com/paritytech//cumulus", rev = "a63ca3a370d0b1c2743b7d6fac4690a8a9ccff2d" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech//cumulus", rev = "a63ca3a370d0b1c2743b7d6fac4690a8a9ccff2d" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech//cumulus", rev = "a63ca3a370d0b1c2743b7d6fac4690a8a9ccff2d" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech//cumulus", rev = "a63ca3a370d0b1c2743b7d6fac4690a8a9ccff2d" }
parachain-info = { git = "https://github.com/paritytech//cumulus", rev = "a63ca3a370d0b1c2743b7d6fac4690a8a9ccff2d" }

[patch.'https://github.com/paritytech/polkadot']
pallet-xcm = { git = "https://github.com/paritytech//polkadot", rev = "32dd0c9cfcd1a1bda821747f6ab334f0e3577558" }
polkadot-core-primitives = { git = "https://github.com/paritytech//polkadot", rev = "32dd0c9cfcd1a1bda821747f6ab334f0e3577558" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech//polkadot", rev = "32dd0c9cfcd1a1bda821747f6ab334f0e3577558" }
polkadot-parachain = { git = "https://github.com/paritytech//polkadot", rev = "32dd0c9cfcd1a1bda821747f6ab334f0e3577558" }
polkadot-primitives = { git = "https://github.com/paritytech//polkadot", rev = "32dd0c9cfcd1a1bda821747f6ab334f0e3577558" }
xcm = { git = "https://github.com/paritytech//polkadot", rev = "32dd0c9cfcd1a1bda821747f6ab334f0e3577558" }
xcm-executor = { git = "https://github.com/paritytech//polkadot", rev = "32dd0c9cfcd1a1bda821747f6ab334f0e3577558" }
xcm-builder = { git = "https://github.com/paritytech//polkadot", rev = "32dd0c9cfcd1a1bda821747f6ab334f0e3577558" }
xcm-simulator = { git = "https://github.com/paritytech//polkadot", rev = "32dd0c9cfcd1a1bda821747f6ab334f0e3577558" }

[pathch.'https://github.com/open-web3-stack/open-runtime-module-library']
orml-asset-registry = { git = "https://github.com/open-web3-stack//open-runtime-module-library", branch= "polkadot-v0.9.28" }
orml-currencies = { git = "https://github.com/open-web3-stack//open-runtime-module-library", branch= "polkadot-v0.9.28" }
orml-tokens = { git = "https://github.com/open-web3-stack//open-runtime-module-library", branch= "polkadot-v0.9.28" }
orml-traits = { git = "https://github.com/open-web3-stack//open-runtime-module-library", branch= "polkadot-v0.9.28" }
orml-unknown-tokens = { git = "https://github.com/open-web3-stack//open-runtime-module-library", branch= "polkadot-v0.9.28" }
orml-xcm = { git = "https://github.com/open-web3-stack//open-runtime-module-library", branch= "polkadot-v0.9.28" }
orml-xcm-support = { git = "https://github.com/open-web3-stack//open-runtime-module-library", branch= "polkadot-v0.9.28" }
orml-xtokens = { git = "https://github.com/open-web3-stack//open-runtime-module-library", branch= "polkadot-v0.9.28" }
