// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_tangram
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-03-21, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/node-template
// benchmark
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_tangram
// --extrinsic=*
// --steps=20
// --repeat=10
// --raw
// --output=./gamedao-protocol/tangram/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_tangram.
pub trait WeightInfo {
	fn create_realm() -> Weight;
	fn create_class() -> Weight;
	fn create_item() -> Weight;
}

/// Weights for pallet_tangram using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Tangram NextRealmIndex (r:1 w:1)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Tangram RealmByIndex (r:0 w:1)
	// Storage: Tangram Realm (r:0 w:1)
	fn create_realm() -> Weight {
		(26_892_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: Tangram NextRealmIndex (r:1 w:0)
	// Storage: Tangram NextClassIndex (r:1 w:1)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Tangram NextItemIndex (r:0 w:1)
	// Storage: Tangram ItemClass (r:0 w:1)
	// Storage: Tangram MaxItems (r:0 w:1)
	fn create_class() -> Weight {
		(34_493_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: Tangram NextRealmIndex (r:1 w:0)
	// Storage: Tangram NextClassIndex (r:1 w:0)
	// Storage: Tangram NextItemIndex (r:1 w:1)
	// Storage: Tangram MaxItems (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Tangram ItemsForAccount (r:1 w:1)
	// Storage: Tangram Total (r:1 w:1)
	// Storage: Tangram TotalForAccount (r:1 w:1)
	// Storage: Tangram ItemMetadata (r:0 w:1)
	// Storage: Tangram AccountForItem (r:0 w:1)
	// Storage: Tangram Item (r:0 w:1)
	fn create_item() -> Weight {
		(65_702_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(9 as Weight))
			.saturating_add(T::DbWeight::get().writes(7 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Tangram NextRealmIndex (r:1 w:1)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Tangram RealmByIndex (r:0 w:1)
	// Storage: Tangram Realm (r:0 w:1)
	fn create_realm() -> Weight {
		(26_892_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: Tangram NextRealmIndex (r:1 w:0)
	// Storage: Tangram NextClassIndex (r:1 w:1)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Tangram NextItemIndex (r:0 w:1)
	// Storage: Tangram ItemClass (r:0 w:1)
	// Storage: Tangram MaxItems (r:0 w:1)
	fn create_class() -> Weight {
		(34_493_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: Tangram NextRealmIndex (r:1 w:0)
	// Storage: Tangram NextClassIndex (r:1 w:0)
	// Storage: Tangram NextItemIndex (r:1 w:1)
	// Storage: Tangram MaxItems (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Tangram ItemsForAccount (r:1 w:1)
	// Storage: Tangram Total (r:1 w:1)
	// Storage: Tangram TotalForAccount (r:1 w:1)
	// Storage: Tangram ItemMetadata (r:0 w:1)
	// Storage: Tangram AccountForItem (r:0 w:1)
	// Storage: Tangram Item (r:0 w:1)
	fn create_item() -> Weight {
		(65_702_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(9 as Weight))
			.saturating_add(RocksDbWeight::get().writes(7 as Weight))
	}
}
