/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IControl {
  export type MemberStruct = {
    state: BigNumberish;
    joinedAt: BigNumberish;
    totalContribution: BigNumberish;
    role: BytesLike;
    stakedAmount: BigNumberish;
  };

  export type MemberStructOutput = [
    state: bigint,
    joinedAt: bigint,
    totalContribution: bigint,
    role: string,
    stakedAmount: bigint
  ] & {
    state: bigint;
    joinedAt: bigint;
    totalContribution: bigint;
    role: string;
    stakedAmount: bigint;
  };

  export type OrganizationStruct = {
    index: BigNumberish;
    creator: AddressLike;
    prime: AddressLike;
    name: string;
    metadataURI: string;
    orgType: BigNumberish;
    accessModel: BigNumberish;
    feeModel: BigNumberish;
    membershipFee: BigNumberish;
    treasury: AddressLike;
    memberLimit: BigNumberish;
    state: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type OrganizationStructOutput = [
    index: bigint,
    creator: string,
    prime: string,
    name: string,
    metadataURI: string,
    orgType: bigint,
    accessModel: bigint,
    feeModel: bigint,
    membershipFee: bigint,
    treasury: string,
    memberLimit: bigint,
    state: bigint,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    index: bigint;
    creator: string;
    prime: string;
    name: string;
    metadataURI: string;
    orgType: bigint;
    accessModel: bigint;
    feeModel: bigint;
    membershipFee: bigint;
    treasury: string;
    memberLimit: bigint;
    state: bigint;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface IControlInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMember"
      | "canJoinOrganization"
      | "createOrganization"
      | "getGameStakeRequired"
      | "getMember"
      | "getMemberCount"
      | "getOrganization"
      | "getOrganizationCount"
      | "getTreasuryAddress"
      | "hasRole"
      | "isMemberActive"
      | "isOrganizationActive"
      | "removeMember"
      | "setOrganizationState"
      | "spendTreasuryFunds"
      | "updateMemberState"
      | "updateOrganization"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MemberAdded"
      | "MemberRemoved"
      | "MemberStateChanged"
      | "MembershipFeeUpdated"
      | "OrganizationCreated"
      | "OrganizationStateChanged"
      | "OrganizationUpdated"
      | "TreasuryFundsSpent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMember",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canJoinOrganization",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createOrganization",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameStakeRequired",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMember",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrganization",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrganizationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isMemberActive",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOrganizationActive",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOrganizationState",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "spendTreasuryFunds",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMemberState",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOrganization",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "canJoinOrganization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createOrganization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGameStakeRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMemberCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrganization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrganizationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isMemberActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOrganizationActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOrganizationState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spendTreasuryFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMemberState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOrganization",
    data: BytesLike
  ): Result;
}

export namespace MemberAddedEvent {
  export type InputTuple = [
    orgId: BytesLike,
    member: AddressLike,
    state: BigNumberish,
    fee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orgId: string,
    member: string,
    state: bigint,
    fee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orgId: string;
    member: string;
    state: bigint;
    fee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRemovedEvent {
  export type InputTuple = [
    orgId: BytesLike,
    member: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [orgId: string, member: string, timestamp: bigint];
  export interface OutputObject {
    orgId: string;
    member: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberStateChangedEvent {
  export type InputTuple = [
    orgId: BytesLike,
    member: AddressLike,
    oldState: BigNumberish,
    newState: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orgId: string,
    member: string,
    oldState: bigint,
    newState: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orgId: string;
    member: string;
    oldState: bigint;
    newState: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MembershipFeeUpdatedEvent {
  export type InputTuple = [
    orgId: BytesLike,
    oldFee: BigNumberish,
    newFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orgId: string,
    oldFee: bigint,
    newFee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orgId: string;
    oldFee: bigint;
    newFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrganizationCreatedEvent {
  export type InputTuple = [
    orgId: BytesLike,
    creator: AddressLike,
    prime: AddressLike,
    name: string,
    orgType: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orgId: string,
    creator: string,
    prime: string,
    name: string,
    orgType: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orgId: string;
    creator: string;
    prime: string;
    name: string;
    orgType: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrganizationStateChangedEvent {
  export type InputTuple = [
    orgId: BytesLike,
    oldState: BigNumberish,
    newState: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orgId: string,
    oldState: bigint,
    newState: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orgId: string;
    oldState: bigint;
    newState: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrganizationUpdatedEvent {
  export type InputTuple = [
    orgId: BytesLike,
    prime: AddressLike,
    orgType: BigNumberish,
    accessModel: BigNumberish,
    memberLimit: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orgId: string,
    prime: string,
    orgType: bigint,
    accessModel: bigint,
    memberLimit: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    orgId: string;
    prime: string;
    orgType: bigint;
    accessModel: bigint;
    memberLimit: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryFundsSpentEvent {
  export type InputTuple = [
    orgId: BytesLike,
    beneficiary: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    purpose: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orgId: string,
    beneficiary: string,
    token: string,
    amount: bigint,
    purpose: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    orgId: string;
    beneficiary: string;
    token: string;
    amount: bigint;
    purpose: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IControl extends BaseContract {
  contractName: "IControl";

  connect(runner?: ContractRunner | null): IControl;
  waitForDeployment(): Promise<this>;

  interface: IControlInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMember: TypedContractMethod<
    [orgId: BytesLike, member: AddressLike],
    [void],
    "nonpayable"
  >;

  canJoinOrganization: TypedContractMethod<
    [orgId: BytesLike, member: AddressLike],
    [boolean],
    "view"
  >;

  createOrganization: TypedContractMethod<
    [
      name: string,
      metadataURI: string,
      orgType: BigNumberish,
      accessModel: BigNumberish,
      feeModel: BigNumberish,
      memberLimit: BigNumberish,
      membershipFee: BigNumberish,
      gameStakeRequired: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getGameStakeRequired: TypedContractMethod<
    [orgId: BytesLike],
    [bigint],
    "view"
  >;

  getMember: TypedContractMethod<
    [orgId: BytesLike, member: AddressLike],
    [IControl.MemberStructOutput],
    "view"
  >;

  getMemberCount: TypedContractMethod<[orgId: BytesLike], [bigint], "view">;

  getOrganization: TypedContractMethod<
    [orgId: BytesLike],
    [IControl.OrganizationStructOutput],
    "view"
  >;

  getOrganizationCount: TypedContractMethod<[], [bigint], "view">;

  getTreasuryAddress: TypedContractMethod<[orgId: BytesLike], [string], "view">;

  hasRole: TypedContractMethod<
    [orgId: BytesLike, member: AddressLike, role: BytesLike],
    [boolean],
    "view"
  >;

  isMemberActive: TypedContractMethod<
    [orgId: BytesLike, member: AddressLike],
    [boolean],
    "view"
  >;

  isOrganizationActive: TypedContractMethod<
    [orgId: BytesLike],
    [boolean],
    "view"
  >;

  removeMember: TypedContractMethod<
    [orgId: BytesLike, member: AddressLike],
    [void],
    "nonpayable"
  >;

  setOrganizationState: TypedContractMethod<
    [orgId: BytesLike, newState: BigNumberish],
    [void],
    "nonpayable"
  >;

  spendTreasuryFunds: TypedContractMethod<
    [
      orgId: BytesLike,
      token: AddressLike,
      beneficiary: AddressLike,
      amount: BigNumberish,
      purpose: string
    ],
    [void],
    "nonpayable"
  >;

  updateMemberState: TypedContractMethod<
    [orgId: BytesLike, member: AddressLike, newState: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateOrganization: TypedContractMethod<
    [
      orgId: BytesLike,
      newPrime: AddressLike,
      orgType: BigNumberish,
      accessModel: BigNumberish,
      memberLimit: BigNumberish,
      feeModel: BigNumberish,
      membershipFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMember"
  ): TypedContractMethod<
    [orgId: BytesLike, member: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canJoinOrganization"
  ): TypedContractMethod<
    [orgId: BytesLike, member: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "createOrganization"
  ): TypedContractMethod<
    [
      name: string,
      metadataURI: string,
      orgType: BigNumberish,
      accessModel: BigNumberish,
      feeModel: BigNumberish,
      memberLimit: BigNumberish,
      membershipFee: BigNumberish,
      gameStakeRequired: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGameStakeRequired"
  ): TypedContractMethod<[orgId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMember"
  ): TypedContractMethod<
    [orgId: BytesLike, member: AddressLike],
    [IControl.MemberStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMemberCount"
  ): TypedContractMethod<[orgId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOrganization"
  ): TypedContractMethod<
    [orgId: BytesLike],
    [IControl.OrganizationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrganizationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTreasuryAddress"
  ): TypedContractMethod<[orgId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [orgId: BytesLike, member: AddressLike, role: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isMemberActive"
  ): TypedContractMethod<
    [orgId: BytesLike, member: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOrganizationActive"
  ): TypedContractMethod<[orgId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeMember"
  ): TypedContractMethod<
    [orgId: BytesLike, member: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOrganizationState"
  ): TypedContractMethod<
    [orgId: BytesLike, newState: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "spendTreasuryFunds"
  ): TypedContractMethod<
    [
      orgId: BytesLike,
      token: AddressLike,
      beneficiary: AddressLike,
      amount: BigNumberish,
      purpose: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMemberState"
  ): TypedContractMethod<
    [orgId: BytesLike, member: AddressLike, newState: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateOrganization"
  ): TypedContractMethod<
    [
      orgId: BytesLike,
      newPrime: AddressLike,
      orgType: BigNumberish,
      accessModel: BigNumberish,
      memberLimit: BigNumberish,
      feeModel: BigNumberish,
      membershipFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MemberAdded"
  ): TypedContractEvent<
    MemberAddedEvent.InputTuple,
    MemberAddedEvent.OutputTuple,
    MemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRemoved"
  ): TypedContractEvent<
    MemberRemovedEvent.InputTuple,
    MemberRemovedEvent.OutputTuple,
    MemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "MemberStateChanged"
  ): TypedContractEvent<
    MemberStateChangedEvent.InputTuple,
    MemberStateChangedEvent.OutputTuple,
    MemberStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "MembershipFeeUpdated"
  ): TypedContractEvent<
    MembershipFeeUpdatedEvent.InputTuple,
    MembershipFeeUpdatedEvent.OutputTuple,
    MembershipFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OrganizationCreated"
  ): TypedContractEvent<
    OrganizationCreatedEvent.InputTuple,
    OrganizationCreatedEvent.OutputTuple,
    OrganizationCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrganizationStateChanged"
  ): TypedContractEvent<
    OrganizationStateChangedEvent.InputTuple,
    OrganizationStateChangedEvent.OutputTuple,
    OrganizationStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "OrganizationUpdated"
  ): TypedContractEvent<
    OrganizationUpdatedEvent.InputTuple,
    OrganizationUpdatedEvent.OutputTuple,
    OrganizationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryFundsSpent"
  ): TypedContractEvent<
    TreasuryFundsSpentEvent.InputTuple,
    TreasuryFundsSpentEvent.OutputTuple,
    TreasuryFundsSpentEvent.OutputObject
  >;

  filters: {
    "MemberAdded(bytes32,address,uint8,uint256,uint256)": TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;
    MemberAdded: TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;

    "MemberRemoved(bytes32,address,uint256)": TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;
    MemberRemoved: TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;

    "MemberStateChanged(bytes32,address,uint8,uint8,uint256)": TypedContractEvent<
      MemberStateChangedEvent.InputTuple,
      MemberStateChangedEvent.OutputTuple,
      MemberStateChangedEvent.OutputObject
    >;
    MemberStateChanged: TypedContractEvent<
      MemberStateChangedEvent.InputTuple,
      MemberStateChangedEvent.OutputTuple,
      MemberStateChangedEvent.OutputObject
    >;

    "MembershipFeeUpdated(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      MembershipFeeUpdatedEvent.InputTuple,
      MembershipFeeUpdatedEvent.OutputTuple,
      MembershipFeeUpdatedEvent.OutputObject
    >;
    MembershipFeeUpdated: TypedContractEvent<
      MembershipFeeUpdatedEvent.InputTuple,
      MembershipFeeUpdatedEvent.OutputTuple,
      MembershipFeeUpdatedEvent.OutputObject
    >;

    "OrganizationCreated(bytes32,address,address,string,uint8,uint256)": TypedContractEvent<
      OrganizationCreatedEvent.InputTuple,
      OrganizationCreatedEvent.OutputTuple,
      OrganizationCreatedEvent.OutputObject
    >;
    OrganizationCreated: TypedContractEvent<
      OrganizationCreatedEvent.InputTuple,
      OrganizationCreatedEvent.OutputTuple,
      OrganizationCreatedEvent.OutputObject
    >;

    "OrganizationStateChanged(bytes32,uint8,uint8,uint256)": TypedContractEvent<
      OrganizationStateChangedEvent.InputTuple,
      OrganizationStateChangedEvent.OutputTuple,
      OrganizationStateChangedEvent.OutputObject
    >;
    OrganizationStateChanged: TypedContractEvent<
      OrganizationStateChangedEvent.InputTuple,
      OrganizationStateChangedEvent.OutputTuple,
      OrganizationStateChangedEvent.OutputObject
    >;

    "OrganizationUpdated(bytes32,address,uint8,uint8,uint32,uint256)": TypedContractEvent<
      OrganizationUpdatedEvent.InputTuple,
      OrganizationUpdatedEvent.OutputTuple,
      OrganizationUpdatedEvent.OutputObject
    >;
    OrganizationUpdated: TypedContractEvent<
      OrganizationUpdatedEvent.InputTuple,
      OrganizationUpdatedEvent.OutputTuple,
      OrganizationUpdatedEvent.OutputObject
    >;

    "TreasuryFundsSpent(bytes32,address,address,uint256,string,uint256)": TypedContractEvent<
      TreasuryFundsSpentEvent.InputTuple,
      TreasuryFundsSpentEvent.OutputTuple,
      TreasuryFundsSpentEvent.OutputObject
    >;
    TreasuryFundsSpent: TypedContractEvent<
      TreasuryFundsSpentEvent.InputTuple,
      TreasuryFundsSpentEvent.OutputTuple,
      TreasuryFundsSpentEvent.OutputObject
    >;
  };
}
