/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as controlRefactoredSol from "./ControlRefactored.sol";
export { Control__factory } from "./Control__factory";
