/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iGameTokenSol from "./IGameToken.sol";
export * as iGameTokenCleanSol from "./IGameTokenClean.sol";
export { IControl__factory } from "./IControl__factory";
export { IFlow__factory } from "./IFlow__factory";
export { IGameDAOModule__factory } from "./IGameDAOModule__factory";
export { IGameDAORegistry__factory } from "./IGameDAORegistry__factory";
export { IGameStaking__factory } from "./IGameStaking__factory";
export { IIdentity__factory } from "./IIdentity__factory";
export { ISense__factory } from "./ISense__factory";
export { ISignal__factory } from "./ISignal__factory";
