
//! Autogenerated weights for gamedao_sense
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-10, STEPS: `20`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/subzero-dev
// benchmark
// pallet
// --execution=wasm
// --pallet=gamedao_sense
// --extrinsic=*
// --steps=20
// --repeat=10
// --output=modules/gamedao-protocol/sense/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for gamedao_sense.
pub trait WeightInfo {
	fn create_entity() -> Weight;
	fn update_property() -> Weight;
}

/// Weights for gamedao_sense using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Sense Entities (r:1 w:1)
	// Storage: Sense EntityCount (r:1 w:1)
	// Storage: Sense Properties (r:0 w:3)
	fn create_entity() -> Weight {
		// Minimum execution time: 27_000 nanoseconds.
		Weight::from_ref_time(29_000_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	// Storage: Sense Entities (r:1 w:0)
	// Storage: Sense Properties (r:1 w:1)
	fn update_property() -> Weight {
		// Minimum execution time: 25_000 nanoseconds.
		Weight::from_ref_time(26_000_000)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Sense Entities (r:1 w:1)
	// Storage: Sense EntityCount (r:1 w:1)
	// Storage: Sense Properties (r:0 w:3)
	fn create_entity() -> Weight {
		// Minimum execution time: 27_000 nanoseconds.
		Weight::from_ref_time(29_000_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(5))
	}
	// Storage: Sense Entities (r:1 w:0)
	// Storage: Sense Properties (r:1 w:1)
	fn update_property() -> Weight {
		// Minimum execution time: 25_000 nanoseconds.
		Weight::from_ref_time(26_000_000)
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}