#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Path to contract artifacts
const artifactsPath = path.join(__dirname, '../../contracts-solidity/artifacts/contracts');
const outputPath = path.join(__dirname, '../src/abis.ts');

// Contract mapping - maps contract paths to their export names
const contractMapping = {
  // Core contracts
  'core/Registry.sol/Registry.json': 'REGISTRY_ABI',
  'modules/Control/Control.sol/Control.json': 'CONTROL_ABI',
  'modules/Control/Factory.sol/Factory.json': 'FACTORY_ABI',
  'modules/Membership/Membership.sol/Membership.json': 'MEMBERSHIP_ABI',
  'modules/Flow/Flow.sol/Flow.json': 'FLOW_ABI',
  'modules/Signal/Signal.sol/Signal.json': 'SIGNAL_ABI',
  'modules/Sense/Sense.sol/Sense.json': 'SENSE_ABI',
  'modules/Identity/Identity.sol/Identity.json': 'IDENTITY_ABI',
  'modules/Staking/Staking.sol/Staking.json': 'STAKING_ABI',
  'core/Treasury.sol/Treasury.json': 'TREASURY_ABI',

  // Token contracts
  'tokens/GameToken.sol/GameToken.json': 'GAME_TOKEN_ABI',
  'mocks/MockGameToken.sol/MockGameToken.json': 'MOCK_GAME_TOKEN_ABI',
  'mocks/MockUSDC.sol/MockUSDC.json': 'MOCK_USDC_ABI'
};

function generateAbis() {
  console.log('🔍 Generating ABIs from contract artifacts...');

  if (!fs.existsSync(artifactsPath)) {
    console.log('⚠️  Artifacts directory not found — using committed abis.ts');
    if (fs.existsSync(outputPath)) {
      console.log('✅ Existing abis.ts preserved');
      return;
    }
    console.error('❌ No artifacts and no existing abis.ts — compile contracts first');
    process.exit(1);
  }

  let content = `import { Abi } from 'viem';

// Auto-generated ABIs from contract compilation
// Do not edit this file manually

`;

  const exportedAbis = [];

  // Generate ABIs for each contract
  for (const [contractPath, exportName] of Object.entries(contractMapping)) {
    const fullPath = path.join(artifactsPath, contractPath);

    if (!fs.existsSync(fullPath)) {
      console.log(`⚠️  Contract artifact not found: ${contractPath}`);
      continue;
    }

    try {
      const artifact = JSON.parse(fs.readFileSync(fullPath, 'utf8'));

      if (!artifact.abi) {
        console.log(`⚠️  No ABI found in ${contractPath}`);
        continue;
      }

      const abiString = JSON.stringify(artifact.abi, null, 2);

      content += `export const ${exportName} = ${abiString} as const satisfies Abi;\n\n`;
      exportedAbis.push(exportName);

      console.log(`✅ Generated ABI for ${exportName}`);
    } catch (error) {
      console.error(`❌ Error processing ${contractPath}:`, error.message);
    }
  }

  // Build CONTRACT_NAMES and ABIS only from successfully generated ABIs
  const nameMap = {
    REGISTRY_ABI: 'Registry', CONTROL_ABI: 'Control', FACTORY_ABI: 'Factory',
    MEMBERSHIP_ABI: 'Membership', FLOW_ABI: 'Flow', SIGNAL_ABI: 'Signal',
    SENSE_ABI: 'Sense', IDENTITY_ABI: 'Identity', STAKING_ABI: 'Staking',
    TREASURY_ABI: 'Treasury', GAME_TOKEN_ABI: 'GameToken',
    MOCK_GAME_TOKEN_ABI: 'MockGameToken', MOCK_USDC_ABI: 'MockUSDC',
  };

  const namesEntries = exportedAbis
    .filter(name => nameMap[name])
    .map(name => `  ${name.replace('_ABI', '')}: '${nameMap[name]}'`)
    .join(',\n');

  const abisEntries = exportedAbis
    .map(name => `  ${name.replace('_ABI', '')}: ${name}`)
    .join(',\n');

  content += `// Export contract names for convenience
export const CONTRACT_NAMES = {
${namesEntries}
} as const;

// Export all ABIs as a single object for convenience
export const ABIS = {
${abisEntries}
} as const;
`;

  // Write the file
  fs.writeFileSync(outputPath, content);

  console.log(`✅ Generated ${exportedAbis.length} ABIs in ${outputPath}`);
  console.log(`🎉 ABI generation complete!`);
}

// Run the generation
if (require.main === module) {
  generateAbis();
}

module.exports = { generateAbis };
